[build]
  command = "npm run build"
  publish = "dist/spa"

[build.environment]
  NODE_VERSION = "20.17.0"
  VITE_SUPABASE_URL = "$VITE_SUPABASE_URL"
  VITE_SUPABASE_ANON_KEY = "$VITE_SUPABASE_ANON_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
