[build]
  command = "npm run build"
  publish = "dist/spa"

[build.environment]
<<<<<<< HEAD
  NODE_VERSION = "20"
  # Force Netlify to use environment variables from dashboard
  VITE_SUPABASE_URL = "$VITE_SUPABASE_URL"
  VITE_SUPABASE_ANON_KEY = "$VITE_SUPABASE_ANON_KEY"
=======
  NODE_VERSION = "20.17.0"
>>>>>>> refs/remotes/origin/main

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
